sap.ui.define([
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device"
], function (JSONModel, Device) {
	"use strict";

	return {

		createDeviceModel: function () {
			var oModel = new JSONModel(Device);
			oModel.setDefaultBindingMode("OneWay");
			return oModel;
		},
		_columnList: function () {
			return {
				"CustomRosterColumnBinding": [
					{
					"id": "listClmnJobTitle",
					"headerSpan": "1",
					"width": "14rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Job Title",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>JOB_TITLE}",
					"sEnabled": false,
					"sControl": "ComboBox",
					"sModel": "RosteringListModel>/jobTitles",
					"sItemText": "{RosteringListModel>jobTitleDesc}",
					"sItemKey": "{RosteringListModel>jobTitleDesc}",
				}, {
					"id": "listClmnPosition",
					"headerSpan": "1",
					"width": "12.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Roster Positions",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>ROSTER_NAME_SEQ_NO}",
					"sEnabled": false,
					"sControl": "Input"

				}, {
					"id": "listClmn000",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>000}",
					"nameBinding": "{RosteringListModel>000_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn001",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>001}",
					"nameBinding": "{RosteringListModel>001_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn010",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>010}",
					"nameBinding": "{RosteringListModel>010_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn011",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>011}",
					"nameBinding": "{RosteringListModel>011_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn020",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>020}",
					"nameBinding": "{RosteringListModel>020_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn021",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1/ Day 8",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>021}",
					"nameBinding": "{RosteringListModel>021_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn100",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>100}",
					"nameBinding": "{RosteringListModel>100_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn101",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>101}",
					"nameBinding": "{RosteringListModel>101_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn110",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>110}",
					"nameBinding": "{RosteringListModel>110_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn111",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>111}",
					"nameBinding": "{RosteringListModel>111_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn120",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>120}",
					"nameBinding": "{RosteringListModel>120_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn121",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2/ Day 9",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>121}",
					"nameBinding": "{RosteringListModel>121_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn200",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>200}",
					"nameBinding": "{RosteringListModel>200_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn201",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>201}",
					"nameBinding": "{RosteringListModel>201_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn210",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>210}",
					"nameBinding": "{RosteringListModel>210_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn211",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>211}",
					"nameBinding": "{RosteringListModel>211_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn220",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>220}",
					"nameBinding": "{RosteringListModel>220_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn221",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3/ Day 10",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>221}",
					"nameBinding": "{RosteringListModel>221_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn300",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>300}",
					"nameBinding": "{RosteringListModel>300_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn301",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>301}",
					"nameBinding": "{RosteringListModel>301_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn310",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>310}",
					"nameBinding": "{RosteringListModel>310_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn311",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>311}",
					"nameBinding": "{RosteringListModel>311_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn320",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>320}",
					"nameBinding": "{RosteringListModel>320_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn321",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4/ Day 11",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>321}",
					"nameBinding": "{RosteringListModel>321_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn400",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>400}",
					"nameBinding": "{RosteringListModel>400_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn401",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>401}",
					"nameBinding": "{RosteringListModel>401_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn410",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>410}",
					"nameBinding": "{RosteringListModel>410_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn411",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>411}",
					"nameBinding": "{RosteringListModel>411_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn420",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>420}",
					"nameBinding": "{RosteringListModel>420_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn421",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5/ Day 12",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>421}",
					"nameBinding": "{RosteringListModel>421_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn500",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>500}",
					"nameBinding": "{RosteringListModel>500_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn501",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>501}",
					"nameBinding": "{RosteringListModel>501_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn510",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>510}",
					"nameBinding": "{RosteringListModel>510_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn511",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>511}",
					"nameBinding": "{RosteringListModel>511_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn520",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>520}",
					"nameBinding": "{RosteringListModel>520_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn521",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6/ Day 13",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>521}",
					"nameBinding": "{RosteringListModel>521_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn600",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>600}",
					"nameBinding": "{RosteringListModel>600_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn601",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>601}",
					"nameBinding": "{RosteringListModel>601_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn610",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>610}",
					"nameBinding": "{RosteringListModel>610_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn611",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>611}",
					"nameBinding": "{RosteringListModel>611_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn620",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>620}",
					"nameBinding": "{RosteringListModel>620_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn621",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7/ Day 14",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>621}",
					"nameBinding": "{RosteringListModel>621_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}],
				"ColumnBinding": [
					{
					"id": "listClmnJobTitle",
					"headerSpan": "1",
					"width": "10rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Job Title",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>JOB_TITLE}",
					"sEnabled": false,
					"sControl": "ComboBox",
					"sModel": "RosteringListModel>/jobTitles",
					"sItemText": "{RosteringListModel>jobTitleDesc}",
					"sItemKey": "{RosteringListModel>jobTitleDesc}",
				}, {
					"id": "listClmnPosition",
					"headerSpan": "1",
					"width": "8rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "",
						"visible": false
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Roster Positions",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>ROSTER_NAME_SEQ_NO}",
					"sEnabled": false,
					"sControl": "Input"

				}, {
					"id": "listClmn000",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>000}",
					"nameBinding": "{RosteringListModel>000_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn001",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>001}",
					"nameBinding": "{RosteringListModel>001_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn010",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>010}",
					"nameBinding": "{RosteringListModel>010_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn011",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>011}",
					"nameBinding": "{RosteringListModel>011_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn020",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>020}",
					"nameBinding": "{RosteringListModel>020_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn021",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 1",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>021}",
					"nameBinding": "{RosteringListModel>021_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn100",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>100}",
					"nameBinding": "{RosteringListModel>100_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn101",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>101}",
					"nameBinding": "{RosteringListModel>101_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn110",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>110}",
					"nameBinding": "{RosteringListModel>110_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn111",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>111}",
					"nameBinding": "{RosteringListModel>111_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn120",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>120}",
					"nameBinding": "{RosteringListModel>120_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn121",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 2",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>121}",
					"nameBinding": "{RosteringListModel>121_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn200",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>200}",
					"nameBinding": "{RosteringListModel>200_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn201",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>201}",
					"nameBinding": "{RosteringListModel>201_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn210",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>210}",
					"nameBinding": "{RosteringListModel>210_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn211",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>211}",
					"nameBinding": "{RosteringListModel>211_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn220",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>220}",
					"nameBinding": "{RosteringListModel>220_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn221",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 3",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>221}",
					"nameBinding": "{RosteringListModel>221_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn300",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>300}",
					"nameBinding": "{RosteringListModel>300_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn301",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>301}",
					"nameBinding": "{RosteringListModel>301_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn310",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>310}",
					"nameBinding": "{RosteringListModel>310_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn311",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>311}",
					"nameBinding": "{RosteringListModel>311_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn320",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>320}",
					"nameBinding": "{RosteringListModel>320_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn321",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 4",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>321}",
					"nameBinding": "{RosteringListModel>321_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn400",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>400}",
					"nameBinding": "{RosteringListModel>400_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn401",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>401}",
					"nameBinding": "{RosteringListModel>401_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn410",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>410}",
					"nameBinding": "{RosteringListModel>410_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn411",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>411}",
					"nameBinding": "{RosteringListModel>411_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn420",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>420}",
					"nameBinding": "{RosteringListModel>420_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn421",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 5",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>421}",
					"nameBinding": "{RosteringListModel>421_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn500",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>500}",
					"nameBinding": "{RosteringListModel>500_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn501",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>501}",
					"nameBinding": "{RosteringListModel>501_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn510",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>510}",
					"nameBinding": "{RosteringListModel>510_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn511",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>511}",
					"nameBinding": "{RosteringListModel>511_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn520",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>520}",
					"nameBinding": "{RosteringListModel>520_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn521",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 6",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>521}",
					"nameBinding": "{RosteringListModel>521_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn600",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>600}",
					"nameBinding": "{RosteringListModel>600_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn601",
					"headerSpan": "2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>601}",
					"nameBinding": "{RosteringListModel>601_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn610",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "DAY",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>610}",
					"nameBinding": "{RosteringListModel>610_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn611",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "AM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>611}",
					"nameBinding": "{RosteringListModel>611_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn620",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "Start",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>620}",
					"nameBinding": "{RosteringListModel>620_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}, {
					"id": "listClmn621",
					"headerSpan": "6,2",
					"width": "2.4rem",
					"sortProperty": "",
					"filterProperty": "",
					"labels": [{
						"width": "100%",
						"textAlign": "Center",
						"text": "Day 7",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "PM",
						"visible": true
					}, {
						"width": "100%",
						"textAlign": "Center",
						"text": "End",
						"visible": true
					}],
					"templateBinding": "{RosteringListModel>621}",
					"nameBinding": "{RosteringListModel>621_SEQNO}",
					"sEnabled": true,
					"sControl": "Input"
				}],
				"JobTitle": [{
					"jobTitleDesc": "Chef de Rang"
				}, {
					"jobTitleDesc": "Stateroom Steward(ess)"
				}, {
					"jobTitleDesc": "Hotel Manager"
				}, {
					"jobTitleDesc": "Guest Services Manager"
				}, {
					"jobTitleDesc": "Guest Services Agent"
				}, {
					"jobTitleDesc": "Program Director"
				}, {
					"jobTitleDesc": "Executive Chef"
				}, {
					"jobTitleDesc": "Sous Chef"
				}, {
					"jobTitleDesc": "Chef de Partie"
				}, {
					"jobTitleDesc": "Commis de Cuisine"
				}, {
					"jobTitleDesc": "Utility"
				}, {
					"jobTitleDesc": "Maitre d' Hotel"
				}, {
					"jobTitleDesc": "Bar Chef"
				}, {
					"jobTitleDesc": "Bar Waiter"
				}, {
					"jobTitleDesc": "Housekeeper"
				}, {
					"jobTitleDesc": "Musician"
				}, {
					"jobTitleDesc": "Assistant Maitre d'Hotel"
				}, {
					"jobTitleDesc": "Controller"
				}, {
					"jobTitleDesc": "Laundry Attendant"
				}, {
					"jobTitleDesc": "Guest Technician"
				}, {
					"jobTitleDesc": "F&B Manager"
				}, {
					"jobTitleDesc": "Travel Concierge"
				}, {
					"jobTitleDesc": "Waiter"
				}, {
					"jobTitleDesc": "Stateroom Steward"
				}, {
					"jobTitleDesc": "Lead Travel Concierge"
				}, {
					"jobTitleDesc": "Cook"
				}, {
					"jobTitleDesc": "Assistant Cook"
				}, {
					"jobTitleDesc": "Wok Chef"
				}, {
					"jobTitleDesc": "Night-Auditor"
				}, {
					"jobTitleDesc": "Engineer"
				}, {
					"jobTitleDesc": "Shopping Concierge"
				}, {
					"jobTitleDesc": "Assistent Hotel Manager"
				}, {
					"jobTitleDesc": "Barchef"
				}, {
					"jobTitleDesc": "Assistant Food Beverage Manager"
				}, {
					"jobTitleDesc": "Host"
				}, {
					"jobTitleDesc": "Senior Executive Chef"
				}, {
					"jobTitleDesc": "Senior Hotel Manager"
				}, {
					"jobTitleDesc": "Senior Housekeeper"
				}, {
					"jobTitleDesc": "Destination Manager"
				}, {
					"jobTitleDesc": "Tour Escort"
				}, {
					"jobTitleDesc": "Tour Director"
				}],
				"RosterSample": {
					"Code": "W1",
					"JobTitle": "Chef de Rang",
					"Position": "CHEF DE RANG",
					"000": "07:00",
					"001": "10:00",
					"010": "11:30"	,
					"011": "14:30",
					"020": "17:30",
					"021": "20:30",
					"100": "07:00",
					"101": "10:00",
					"110": "11:30",
					"111": "14:30",
					"120": "17:30",
					"121": "20:30",
					"200": "07:00",
					"201": "10:00",
					"210": "11:30",
					"211": "14:30",
					"220": "17:30",
					"221": "20:30",
					"300": "07:00",
					"301": "10:00",
					"310": "11:30",
					"311": "14:30",
					"320": "17:30",
					"321": "20:30",
					"400": "07:00",
					"401": "10:00",
					"410": "11:30",
					"411": "14:30",
					"420": "17:30",
					"421": "20:30",
					"500": "07:00",
					"501": "10:00",
					"510": "11:30",
					"511": "14:30",
					"520": "17:30",
					"521": "20:30",
					"600": "07:00",
					"601": "10:00",
					"610": "11:30",
					"611": "14:30",
					"620": "17:30",
					"621": "20:30"
				}
			};
		}

	};
});